title: "BitWeav"
description: "Decentralised, secure and reliable peer-to-peer micropublishing."
rights: "Copyright Liam Edwards-Playne and contributors 2013"

siteurl: "bitweav.org"

permalink: pretty
