title: "HTML5 Boilerplate for Jekyll"
description: "Built by Liam Edwards-Playne."
rights: "Copyright Liam Edwards-Playne and contributors 2013"

siteurl: "liamzebedee.github.io/jekyll-html5-template/"

permalink: pretty
