title: "BitWeav"
description: "Simple, secure and sustainable communications by peer-to-peer microblogging and private chat (w/ video)."
rights: "Copyright Liam Edwards-Playne and contributors 2013"

siteurl: "bitweav.org"

permalink: pretty
